/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LearningsLlm101RouteImport } from './routes/learnings.llm-101'
import { Route as LearningsIndexRouteImport } from './routes/learnings.index'
import { Route as LearningsRouteImport } from './routes/learnings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningsRoute = LearningsRouteImport.update({
  id: '/learnings',
  path: '/learnings',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningsIndexRoute = LearningsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearningsRoute,
} as any)
const LearningsLlm101Route = LearningsLlm101RouteImport.update({
  id: '/llm-101',
  path: '/llm-101',
  getParentRoute: () => LearningsRoute,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/learnings': typeof LearningsRouteWithChildren
  '/learnings/': typeof LearningsIndexRoute
  '/learnings/llm-101': typeof LearningsLlm101Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/learnings': typeof LearningsIndexRoute
  '/learnings/llm-101': typeof LearningsLlm101Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/learnings': typeof LearningsRouteWithChildren
  '/learnings/': typeof LearningsIndexRoute
  '/learnings/llm-101': typeof LearningsLlm101Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/experience' | '/projects' | '/learnings' | '/learnings/' | '/learnings/llm-101' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/experience' | '/projects' | '/learnings' | '/learnings/llm-101' | '/sitemap.xml'
  id:
    '__root__' | '/' | '/contact' | '/experience' | '/projects' | '/learnings' | '/learnings/' | '/learnings/llm-101' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface LearningsRouteChildren {
  LearningsIndexRoute: typeof LearningsIndexRoute
  LearningsLlm101Route: typeof LearningsLlm101Route
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  ProjectsRoute: typeof ProjectsRoute
  LearningsRoute: typeof LearningsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learnings': {
      id: '/learnings'
      path: '/learnings'
      fullPath: '/learnings'
      preLoaderRoute: typeof LearningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learnings/': {
      id: '/learnings/'
      path: '/'
      fullPath: '/learnings/'
      preLoaderRoute: typeof LearningsIndexRouteImport
      parentRoute: typeof LearningsRoute
    }
    '/learnings/llm-101': {
      id: '/learnings/llm-101'
      path: '/llm-101'
      fullPath: '/learnings/llm-101'
      preLoaderRoute: typeof LearningsLlm101RouteImport
      parentRoute: typeof LearningsRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const LearningsRouteChildren: LearningsRouteChildren = {
  LearningsIndexRoute: LearningsIndexRoute,
  LearningsLlm101Route: LearningsLlm101Route,
}
const LearningsRouteWithChildren = LearningsRoute._addFileChildren(LearningsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  ProjectsRoute: ProjectsRoute,
  LearningsRoute: LearningsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
